name: ServerIP
author: AspirantiPluginner
api: ["2.1.0", "2.0.0", "3.0.0-ALPHA1", "3.0.0-ALPHA2", "3.0.0"]
version: 1.0.0
main: AspirantiPluginner\ServerIP\Main

commands:
 serverip:
  description: "Utilizza questo comando per visualizzare l'ip del server"
  usage: "/serverip"
  aliases: ["sip"]
  
permissions:
 serverip:
  children:
   serverip.command:
    children:
     serverip.command.serverip:
      default: true
