name: "WhatServerIp"
author: "Qualcuno"
api: "3.0.0alpha3"
version: "1.0.0"
main: Qualche cartella
commands:
 myip:
  description: "quando usi questo comando ti appare scritto l ip del tuo server!"
  usage: "/sip"
permissions:
 myip:
  children:
  default: true
  
 
 
