name: "ExemplePlugin"
author: "Qualcuno"
api: nn so api
version: 1.0.0
main: Qualche cartella
commands:
 teleport:
  description: "Teleport to any point of the wolrd or to any player"
  usage: "/tp (x) (y) (z) / (player), /tp (x) (y) (z) / (player)"
 teleportall:
  description: "Teleport all players to you"
  usage: "/tpall"
permissions:
  teleport:
   default: op
  teleport.all:
   default: op
 
 
 
